export * from '../modules/auth/api/mutations'
export * from '../modules/events/api/mutations'
export * from '../modules/news/api/mutations'
export * from '../modules/products/api/mutations'
export * from '../modules/reservations/api/mutations'
export * from '../modules/users/api/mutations'
export * from '../modules/competitions/api/mutations'
