export * from '../modules/auth/api/queries'
export * from '../modules/events/api/queries'
export * from '../modules/news/api/queries'
export * from '../modules/products/api/queries'
export * from '../modules/reservations/api/queries'
export * from '../modules/users/api/queries'
